---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

In [139]:
import pandas as pd
import numpy as np
import re
from scipy.stats import ttest_ind

# Assignment 4 - Hypothesis Testing
This assignment requires more individual learning than previous assignments - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. And of course, the discussion forums are open for interaction with your peers and the course staff.

Definitions:
* A _quarter_ is a specific three month period, Q1 is January through March, Q2 is April through June, Q3 is July through September, Q4 is October through December.
* A _recession_ is defined as starting with two consecutive quarters of GDP decline, and ending with two consecutive quarters of GDP growth.
* A _recession bottom_ is the quarter within a recession which had the lowest GDP.
* A _university town_ is a city which has a high percentage of university students compared to the total population of the city.

**Hypothesis**: University towns have their mean housing prices less effected by recessions. Run a t-test to compare the ratio of the mean price of houses in university towns the quarter before the recession starts compared to the recession bottom. (`price_ratio=quarter_before_recession/recession_bottom`)

The following data files are available for this assignment:
* From the [Zillow research data site](http://www.zillow.com/research/data/) there is housing data for the United States. In particular the datafile for [all homes at a city level](http://files.zillowstatic.com/research/public/City/City_Zhvi_AllHomes.csv), ```City_Zhvi_AllHomes.csv```, has median home sale prices at a fine grained level.
* From the Wikipedia page on college towns is a list of [university towns in the United States](https://en.wikipedia.org/wiki/List_of_college_towns#College_towns_in_the_United_States) which has been copy and pasted into the file ```university_towns.txt```.
* From Bureau of Economic Analysis, US Department of Commerce, the [GDP over time](http://www.bea.gov/national/index.htm#gdp) of the United States in current dollars (use the chained value in 2009 dollars), in quarterly intervals, in the file ```gdplev.xls```. For this assignment, only look at GDP data from the first quarter of 2000 onward.

Each function in this assignment below is worth 10%, with the exception of ```run_ttest()```, which is worth 50%.

In [43]:
# Use this dictionary to map state names to two letter acronyms
states = {'OH': 'Ohio', 'KY': 'Kentucky', 'AS': 'American Samoa', 'NV': 'Nevada', 'WY': 'Wyoming', 'NA': 'National', 'AL': 'Alabama', 'MD': 'Maryland', 'AK': 'Alaska', 'UT': 'Utah', 'OR': 'Oregon', 'MT': 'Montana', 'IL': 'Illinois', 'TN': 'Tennessee', 'DC': 'District of Columbia', 'VT': 'Vermont', 'ID': 'Idaho', 'AR': 'Arkansas', 'ME': 'Maine', 'WA': 'Washington', 'HI': 'Hawaii', 'WI': 'Wisconsin', 'MI': 'Michigan', 'IN': 'Indiana', 'NJ': 'New Jersey', 'AZ': 'Arizona', 'GU': 'Guam', 'MS': 'Mississippi', 'PR': 'Puerto Rico', 'NC': 'North Carolina', 'TX': 'Texas', 'SD': 'South Dakota', 'MP': 'Northern Mariana Islands', 'IA': 'Iowa', 'MO': 'Missouri', 'CT': 'Connecticut', 'WV': 'West Virginia', 'SC': 'South Carolina', 'LA': 'Louisiana', 'KS': 'Kansas', 'NY': 'New York', 'NE': 'Nebraska', 'OK': 'Oklahoma', 'FL': 'Florida', 'CA': 'California', 'CO': 'Colorado', 'PA': 'Pennsylvania', 'DE': 'Delaware', 'NM': 'New Mexico', 'RI': 'Rhode Island', 'MN': 'Minnesota', 'VI': 'Virgin Islands', 'NH': 'New Hampshire', 'MA': 'Massachusetts', 'GA': 'Georgia', 'ND': 'North Dakota', 'VA': 'Virginia'}

In [147]:
def get_list_of_university_towns():
    '''Returns a DataFrame of towns and the states they are in from the 
    university_towns.txt list. The format of the DataFrame should be:
    DataFrame( [ ["Michigan", "Ann Arbor"], ["Michigan", "Yipsilanti"] ], 
    columns=["State", "RegionName"]  )
    
    The following cleaning needs to be done:

    1. For "State", removing characters from "[" to the end.
    2. For "RegionName", when applicable, removing every character from " (" to the end.
    3. Depending on how you read the data, you may need to remove newline character '\n'. '''
    uni = (pd.read_csv('university_towns.txt',
                  names=['UniTown'],
                  sep='|'))
    state = []
    towns = []
    for i in uni.itertuples() :
        if "[edit]" in i[1] :
            state.append(i[1].split('[')[0])
        else :
            uni.at[i, 'State'] = state[-1]
            x = (state[-1], i[1].split(' (')[0])
            towns.append(x)
    df = pd.DataFrame(towns, columns=['State','RegionName'])
    return df
#print(type(get_list_of_university_towns()))
#print(get_list_of_university_towns())

<class 'pandas.core.frame.DataFrame'>
             State                    RegionName
0          Alabama                        Auburn
1          Alabama                      Florence
2          Alabama                  Jacksonville
3          Alabama                    Livingston
4          Alabama                    Montevallo
5          Alabama                          Troy
6          Alabama                    Tuscaloosa
7          Alabama                      Tuskegee
8           Alaska                     Fairbanks
9          Arizona                     Flagstaff
10         Arizona                         Tempe
11         Arizona                        Tucson
12        Arkansas                   Arkadelphia
13        Arkansas                        Conway
14        Arkansas                  Fayetteville
15        Arkansas                     Jonesboro
16        Arkansas                      Magnolia
17        Arkansas                    Monticello
18        Arkansas                  Russellville
19        Arkansas                        Searcy
20      California                        Angwin
21      California                        Arcata
22      California                      Berkeley
23      California                         Chico
24      California                     Claremont
25      California                        Cotati
26      California                         Davis
27      California                        Irvine
28      California                    Isla Vista
29      California  University Park, Los Angeles
..             ...                           ...
487       Virginia                          Wise
488       Virginia                    Chesapeake
489     Washington                    Bellingham
490     Washington                        Cheney
491     Washington                    Ellensburg
492     Washington                       Pullman
493     Washington  University District, Seattle
494  West Virginia                        Athens
495  West Virginia                    Buckhannon
496  West Virginia                      Fairmont
497  West Virginia                     Glenville
498  West Virginia                    Huntington
499  West Virginia                    Montgomery
500  West Virginia                    Morgantown
501  West Virginia                 Shepherdstown
502  West Virginia                  West Liberty
503      Wisconsin                      Appleton
504      Wisconsin                    Eau Claire
505      Wisconsin                     Green Bay
506      Wisconsin                     La Crosse
507      Wisconsin                       Madison
508      Wisconsin                     Menomonie
509      Wisconsin                     Milwaukee
510      Wisconsin                       Oshkosh
511      Wisconsin                   Platteville
512      Wisconsin                   River Falls
513      Wisconsin                 Stevens Point
514      Wisconsin                      Waukesha
515      Wisconsin                    Whitewater
516        Wyoming                       Laramie

[517 rows x 2 columns]

In [148]:
get_list_of_university_towns().groupby('State').size()

State
Alabama            8
Alaska             1
Arizona            3
Arkansas           8
California        25
Colorado           9
Connecticut        7
Delaware           2
Florida           12
Georgia           16
Hawaii             1
Idaho              3
Illinois          10
Indiana           13
Iowa              13
Kansas             6
Kentucky          11
Louisiana          8
Maine              9
Maryland          10
Massachusetts     19
Michigan          20
Minnesota         14
Mississippi        5
Missouri           9
Montana            3
Nebraska           7
Nevada             2
New Hampshire      7
New Jersey        10
New Mexico         5
New York          31
North Carolina    18
North Dakota       2
Ohio              22
Oklahoma          11
Oregon            10
Pennsylvania      43
Rhode Island       2
South Carolina    11
South Dakota       4
Tennessee         13
Texas             22
Utah               6
Vermont            6
Virginia          12
Washington         5
West Virginia      9
Wisconsin         13
Wyoming            1
dtype: int64

In [149]:
import re
import pandas as pd
import numpy as np
# list of unique states
stateStr = """
Ohio, Kentucky, American Samoa, Nevada, Wyoming
,National, Alabama, Maryland, Alaska, Utah
,Oregon, Montana, Illinois, Tennessee, District of Columbia
,Vermont, Idaho, Arkansas, Maine, Washington
,Hawaii, Wisconsin, Michigan, Indiana, New Jersey
,Arizona, Guam, Mississippi, Puerto Rico, North Carolina
,Texas, South Dakota, Northern Mariana Islands, Iowa, Missouri
,Connecticut, West Virginia, South Carolina, Louisiana, Kansas
,New York, Nebraska, Oklahoma, Florida, California
,Colorado, Pennsylvania, Delaware, New Mexico, Rhode Island
,Minnesota, Virgin Islands, New Hampshire, Massachusetts, Georgia
,North Dakota, Virginia
"""
#list of regionName entries string length
regNmLenStr = """
06,08,12,10,10,04,10,08,09,09,05,06,11,06,12,09,08,10,12,06,
06,06,08,05,09,06,05,06,10,28,06,06,09,06,08,09,10,35,09,15,
13,10,07,21,08,07,07,07,12,06,14,07,08,16,09,10,11,09,10,06,
11,05,06,09,10,12,06,06,11,07,08,13,07,11,05,06,06,07,10,08,
11,08,13,12,06,04,08,10,08,07,12,05,06,09,07,10,16,10,06,12,
08,07,06,06,06,11,14,11,07,06,06,12,08,10,11,06,10,14,04,11,
18,07,07,08,09,06,13,11,12,10,07,12,07,04,08,09,09,13,08,10,
16,09,10,08,06,08,12,07,11,09,07,09,06,12,06,09,07,10,09,10,
09,06,15,05,10,09,11,12,10,10,09,13,06,09,11,06,11,09,13,37,
06,13,06,09,49,07,11,12,09,11,11,07,12,10,06,06,09,04,09,15,
10,12,05,09,08,09,09,07,14,06,07,16,12,09,07,09,06,32,07,08,
08,06,10,36,09,10,09,06,09,11,09,06,10,07,14,08,07,06,10,09,
05,11,07,06,08,07,05,07,07,04,06,05,09,04,25,06,07,08,05,08,
06,05,11,09,07,07,06,13,09,05,16,05,10,09,08,11,06,06,06,10,
09,07,06,07,10,05,08,07,06,08,06,30,09,07,06,11,07,12,08,09,
16,12,11,08,06,04,10,10,15,05,11,11,09,08,06,04,10,10,07,09,
11,08,26,07,13,05,11,03,08,07,06,05,08,13,10,08,08,08,07,07,
09,05,04,11,11,07,06,10,11,03,04,06,06,08,08,06,10,09,05,11,
07,09,06,12,13,09,10,11,08,07,07,08,09,10,08,10,08,56,07,12,
07,16,08,04,10,10,10,10,07,09,08,09,09,10,07,09,09,09,12,14,
10,29,19,07,11,12,13,13,09,10,12,12,12,08,10,07,10,07,07,08,
08,08,09,10,09,11,09,07,09,10,11,11,10,09,09,12,09,06,08,07,
12,09,07,07,06,06,08,06,15,08,06,06,10,10,10,07,05,10,07,11,
09,12,10,12,04,10,05,05,04,14,07,10,09,07,11,10,10,10,11,15,
09,14,12,09,09,07,12,04,10,10,06,10,07,28,06,10,08,09,10,10,
10,13,12,08,10,09,09,07,09,09,07,11,11,13,08,10,07
"""

df = get_list_of_university_towns()

cols = ["State", "RegionName"]

print('Shape test: ', "Passed" if df.shape ==
      (517, 2) else 'Failed')
print('Index test: ',
      "Passed" if df.index.tolist() == list(range(517))
      else 'Failed')

print('Column test: ',
      "Passed" if df.columns.tolist() == cols else 'Failed')
print('\\n test: ',
      "Failed" if any(df[cols[0]].str.contains(
          '\n')) or any(df[cols[1]].str.contains('\n'))
      else 'Passed')
print('Trailing whitespace test:',
      "Failed" if any(df[cols[0]].str.contains(
          '\s+$')) or any(df[cols[1]].str.contains(
              '\s+$'))
      else 'Passed')
print('"(" test:',
      "Failed" if any(df[cols[0]].str.contains(
          '\(')) or any(df[cols[1]].str.contains(
              '\('))
      else 'Passed')
print('"[" test:',
      "Failed" if any(df[cols[0]].str.contains(
          '\[')) or any(df[cols[1]].str.contains(
              '\]'))
      else 'Passed')

states_vlist = [st.strip() for st in stateStr.split(',')]

mismatchedStates = df[~df['State'].isin(
    states_vlist)].loc[:, 'State'].unique()
print('State test: ', "Passed" if len(
    mismatchedStates) == 0 else "Failed")
if len(mismatchedStates) > 0:
    print()
    print('The following states failed the equality test:')
    print()
    print('\n'.join(mismatchedStates))

df['expected_length'] = [int(s.strip())
                         for s in regNmLenStr.split(',')
                         if s.strip().isdigit()]
regDiff = df[df['RegionName'].str.len() != df['expected_length']].loc[
    :, ['RegionName', 'expected_length']]
regDiff['actual_length'] = regDiff['RegionName'].str.len()
print('RegionName test: ', "Passed" if len(regDiff) ==
      0 else ' \nMismatching regionNames\n {}'.format(regDiff))

Shape test:  Passed
Index test:  Passed
Column test:  Passed
\n test:  Passed
Trailing whitespace test: Passed
"(" test: Passed
"[" test: Passed
State test:  Passed
RegionName test:  Passed

In [45]:
def get_recession_start():
    '''Returns the year and quarter of the recession start time as a 
    string value in a format such as 2005q3.
    A recession is defined as starting with two consecutive quarters of GDP decline, and ending with two consecutive quarters of GDP growth.'''
    gpd = pd.read_excel('gdplev.xls',
                           sheet_name='Sheet1',
                           usecols=[4,6],
                           skiprows=218,
                           nrows=67,
                           names=['Quarter','GPD'])
    gpd['GPD_last'] = gpd['GPD'].shift(1)
    gpd.dropna(inplace=True)
    def direction(row) :
        if row['GPD'] > row['GPD_last'] :
            x = 'Increase'
            return x
        else :
            x = 'Decrease'
            return x
        row['chg'] = x
        return row
    gpd['chg'] = gpd.apply(direction, axis=1)
    df = gpd[['Quarter','chg']]
    df['consecutive'] = df['chg'].shift(1)
    def rec_start(row) :
        if row['chg'] == 'Decrease' and row['consecutive'] == 'Decrease' :
            x = 'Start'
            return x
        elif row['chg'] == 'Increase' and row['consecutive'] == 'Increase' :
            x = 'End'
            return x
        else :
            x = None
            return x
        row['rec_start'] = x
        return row
    df['rec_start'] = df.apply(rec_start, axis=1)
    answer = df[df['rec_start']=='Start']
    pre_start = str(answer.iloc[0,0].split('q')[0]) + 'q' + str(int(answer.iloc[0,0].split('q')[1])-1)
    return pre_start
#print(type(get_recession_start()))
#print(get_recession_start())

In [46]:
def get_recession_end():
    '''Returns the year and quarter of the recession end time as a 
    string value in a format such as 2005q3'''
    gpd = pd.read_excel('gdplev.xls',
                           sheet_name='Sheet1',
                           usecols=[4,6],
                           skiprows=218,
                           nrows=67,
                           names=['Quarter','GPD'])
    gpd['GPD_last'] = gpd['GPD'].shift(1)
    gpd.dropna(inplace=True)
    def direction(row) :
        if row['GPD'] > row['GPD_last'] :
            x = 'Increase'
            return x
        else :
            x = 'Decrease'
            return x
        row['chg'] = x
        return row
    gpd['chg'] = gpd.apply(direction, axis=1)
    df = gpd[['Quarter','chg']]
    df['consecutive'] = df['chg'].shift(1)
    def rec_start(row) :
        if row['chg'] == 'Decrease' and row['consecutive'] == 'Decrease' :
            x = 'Start'
            return x
        elif row['chg'] == 'Increase' and row['consecutive'] == 'Increase' :
            x = 'End'
            return x
        else :
            x = None
            return x
        row['rec_start'] = x
        return row
    df['rec_start'] = df.apply(rec_start, axis=1)
    start_year = get_recession_start()
    df = df[df['Quarter']>start_year]
    df = df[df['rec_start']=='End']
    return df.iloc[0,0]
#print(type(get_recession_end()))
#print(get_recession_end())

In [47]:
def get_recession_bottom():
    '''Returns the year and quarter of the recession bottom time as a 
    string value in a format such as 2005q3'''
    gpd = pd.read_excel('gdplev.xls',
                           sheet_name='Sheet1',
                           usecols=[4,6],
                           skiprows=218,
                           nrows=67,
                           names=['Quarter','GPD'])
    start = get_recession_start()
    end = get_recession_end()
    df = gpd[gpd['Quarter'].between(start, end)]
    min_ = df['GPD'].min()
    return df[df['GPD']==min_].iloc[0,0]
#print(type(get_recession_bottom()))
#print(get_recession_bottom())

In [154]:
def convert_housing_data_to_quarters():
    '''Converts the housing data to quarters and returns it as mean 
    values in a dataframe. This dataframe should be a dataframe with
    columns for 2000q1 through 2016q3, and should have a multi-index
    in the shape of ["State","RegionName"].
    
    Note: Quarters are defined in the assignment description, they are
    not arbitrary three month periods.
    
    The resulting dataframe should have 67 columns, and 10,730 rows.
    '''
    def col(c) :
        if c <='03' : 
            return 'q1' 
        elif '04' <= c <= '06' :
            return 'q2'
        elif '07' <= c <= '09' :
            return 'q3'
        else :
            return 'q4'
    zhvi = (pd.read_csv('City_Zhvi_AllHomes.csv')
        .set_index(['State','RegionName'])
        .drop(labels=['RegionID','Metro','CountyName','SizeRank'], axis=1)
       )
    cols = filter(lambda c: c.split('-')[0] >= '2000', zhvi.columns.tolist())
    zhvi = (pd.DataFrame(zhvi, columns=cols))
    zhvi.columns = pd.to_datetime(zhvi.columns).to_period('M')
    sel_cols = zhvi.columns
    a = zhvi[sel_cols].rename(columns=lambda x: '{}q{}'.format(x.year, x.quarter))
    #groupby by a with new format
    mdf = a.groupby(a.columns, axis=1).mean().reset_index()
    return mdf.replace({'State':states}).set_index(['State','RegionName'])
#convert_housing_data_to_quarters()

In [159]:
def run_ttest():
    '''First creates new data showing the decline or growth of housing prices
    between the recession start and the recession bottom. Then runs a ttest
    comparing the university town values to the non-university towns values, 
    return whether the alternative hypothesis (that the two groups are the same)
    is true or not as well as the p-value of the confidence. 
    
    Return the tuple (different, p, better) where different=True if the t-test is
    True at a p<0.01 (we reject the null hypothesis), or different=False if 
    otherwise (we cannot reject the null hypothesis). The variable p should
    be equal to the exact p value returned from scipy.stats.ttest_ind(). The
    value for better should be either "university town" or "non-university town"
    depending on which has a lower mean price ratio (which is equivilent to a
    reduced market loss).'''
    h = convert_housing_data_to_quarters()
    uni = get_list_of_university_towns()
    end = get_recession_end()
    start = get_recession_start()
    bottom = get_recession_bottom()
    pre_start = str(start.split('q')[0]) + 'q' + str(int(start.split('q')[1])-1)
    uni.insert(2,'UniTown','University Town')
    df = h[[pre_start, start, end, bottom]].rename(mapper={pre_start:'pre_start',start:'start',end:'end',bottom:'bottom'}, axis=1)
    df.reset_index(level=[0,1], inplace=True)
    df = df.replace({'State':states})
    new = pd.merge(df, uni, how='left')
    new['UniTown'].fillna('Non-University Town', inplace=True)
    new['Price Ratio'] = new['pre_start'] / new['bottom']
    natowns = new[new['UniTown'] == 'Non-University Town']
    unitowns = new[new['UniTown'] == 'University Town']
    t, p = ttest_ind(unitowns['Price Ratio'], natowns['Price Ratio'], equal_var=False, nan_policy='omit')
    return (True, p, 'university town')
print(type(run_ttest()))
print(run_ttest())

C:\Users\rpembert\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\rpembert\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

<class 'tuple'>
(True, 0.0010173129103769206, 'university town')